# image: https://hub.docker.com/r/javanile/vtiger
# src: https://www.github.com/javanile/vtiger

version: '3.8'

services:

  vtiger:
    image: javanile/vtiger:${APP_VERSION}
    container_name: ${APP_NAME}
    restart: always
    ports:
      - ${APP_HTTP_PORT}:80
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${DB_MYSQL_USER}
      - MYSQL_DATABASE=${DB_MYSQL_NAME}
      - MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
      - VT_ADMIN_USER=${APP_USER}
      - VT_ADMIN_PASSWORD=${APP_PASSWORD}
    volumes:
      - vtiger:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_MYSQL_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_MYSQL_PASSWORD}
      - MYSQL_USER=${DB_MYSQL_USER}
      - MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode=NO_ENGINE_SUBSTITUTION --local_infile=ON
    ports:
      - ${DB_MYSQL_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
  vtiger:

networks:
  default:
    name: ${APP_NETWORK}
    external: true
